name: Merge
description: File a Merge
title: "[Merge]: "
assignees:
  - octocat
body:
  - type: input
    id: merge
    attributes:
      label: Merge Title
      placeholder: Title
    validations:
      required: true
  - type: textarea
    id: description_merge
    attributes:
      label: Merge Details
      placeholder: Tell us about the merge !
    validations:
      required: true
  - type: textarea
    id: description_test
    attributes:
      label: Test Details
      description: Write about your test
      placeholder: Tell us how to test your merge !
    validations:
      required: true